service: "weather-api"
host: "0.0.0.0"
port: "8080"
openweather_api_key: "API_KEY_OPENWEATHER"
weather_api_com_key: "API_KEY_WEATHERAPI" 
weather_now_provider: "openweathermap"
weather_forecast_provider: "weatherapi"
storage_type: "database"
database_url: "sqlite:///weatherclient.db"
local_directory_for_csv: "local_path"
weather_records_file_name: "weather_records.csv"
cities_file_name: "cities_records.csv"