service: "weather-api"
host: "0.0.0.0"
port: "8080"
openweather_api_key: "API_KEY_OPENWEATHER"
weather_api_com_key: "API_KEY_WEATHERAPI"
weather_now_provider: "openweathermap"
weather_forecast_provider: "weatherapi"
storage_type: "database"
database_url: "sqlite:///:memory:"
local_directory_for_csv: "temp_dir"
weather_records_file_name: "temp_weather_file.csv"
cities_file_name: "/temp_cities_file.csv"
