service: "weather-api"
host: "0.0.0.0"
port: "8080"
openweather_api_key: "API_KEY_OPENWEATHER"
weather_api_com_key: "API_KEY_WEATHERAPI" 
weather_now_provider: "openweathermap"
weather_forecast_provider: "weatherapi"
database_storage_type: "database"
csv_storage_type: "csv"
database_url: "sqlite:///weatherclient.db"
directory: "/Users/giovanni.ruzzante/Desktop/PY4E/weather-api/"
file_name: "weather_records.csv"