# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "weather-api-db" ]
  pull_request:
    branches: [ "weather-api-db" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install poetry
        poetry config virtualenvs.in-project true
        poetry install --with dev
        source .venv/bin/activate
        make style
    - name: Test
      run: |
        pip install poetry
        poetry config virtualenvs.in-project true
        poetry install --with dev
        source .venv/bin/activate
        export CONFIG_FILE=config.test.yml
        make test

